import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import Header from "../components/header"
import {ClerkProvider} from "@clerk/nextjs"
import { dark } from "@clerk/themes"
import {Toaster} from "../components/ui/sonner";

const inter = Inter ({ subsets : ["latin"]});


export const metadata: Metadata = {
  title: " Uptraq - Career coach",
  description: "Generated by Aniket Kashid",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (

    <ClerkProvider 
      appearance={{
        baseTheme:dark,
    }}
    >

      <html suppressHydrationWarning>
        <body
          className={` ${inter.className} antialiased h-full flex flex-col`}
          lang="en"
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >

            <Header/>
            <main className="flex-1">{children}</main>

            <Toaster richColors />

            <footer className="bg-muted/50 py-12">
              <p className="container mx-auto px-4 text-center text-gray-200">made with hard work by ANIKET</p>
            </footer>
          </ThemeProvider>
        </body>
      </html>

    </ClerkProvider>
  );
}
